spring.application.name=demoRESTfulAPI
spring.datasource.url=jdbc:mysql://localhost:3306/UserApi
spring.datasource.password=root
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
